### ISSUE TITLE
Set up/propose basic financial infrastructure and governance

### ISSUE THREAD

**Issue by ejaxon** [Open-NC/leadership-tasks#16]
We don't expect to have much money, but there will probably be some and we need to decide how we'll handle.

I know that @ChrisTheDBA and I were on this. I think you were, @sagarmishra, but correct me if wrong. - Eric

**Comment by ChrisTheDBA** [comment]
I will take the first crack at something. You are correct, its the three of us.

**Comment by ChrisTheDBA** [comment]
Video chat 1/15 11:30a

**Comment by ejaxon** [comment]
I'm going to close this - we have a [next steps task](https://github.com/Open-NC/leadership-tasks/issues/23) set up for this track.
