### ISSUE TITLE
Pick a day for a distributed a event - sometime in August

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#2]

**Comment by ejaxon** [comment]
I believe we tentative decided to make it the weekend of 8/10-12 that Code for Charlotte has on their [calendar](https://www.notion.so/2018-Calendar-f0bd79b28f13411d9821080fffbb43fc) for their Hack for Change event.

**Comment by jhibbets** [comment]
Doodle is here: https://doodle.com/poll/kr8khkpmq5cz3f2f

Email sent to confirm date to Open NC leadership.

**Comment by jhibbets** [comment]
August 11, 2018 looks like a consensus.

**Comment by jhibbets** [comment]
Calendar invite added to NC Open Collaborative calendar
