### ISSUE TITLE
Next steps for governance / financial commitee

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#23]
Eric will work with Chris and Sagar
- [x] What responsibilities, expected time commitment
- [x] Set up a google form once we have the candidates

**Comment by ejaxon** [comment]
@jhibbets @ChrisTheDBA @sagarmishra 
Here is the draft announcement about the governance committee and opening nominations: https://docs.google.com/document/d/1TUBadrpdDoDFdE9WQNoMFt96oPQPWKWFH3pMsy33TN0/edit?usp=sharing. Please take a look and let me know by tonight if you have any objections to my posting it on the OpenNC mailing list. I'd like to get things rolling. -Eric

**Comment by jhibbets** [comment]
suggestions made, everything else LGTM.

**Comment by ejaxon** [comment]
Closing this since the governance committee is now off and running.
