### ISSUE TITLE
Review and comment on Who We Are Document

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#34]
https://docs.google.com/document/d/1h00Xf7ilWrKD5gbAy85VqugVHWhumkl39ufVUtV_OLM/edit?usp=sharing

**Comment by ejaxon** [comment]
I made a bunch of changes in suggest-mode.

**Comment by ChrisTheDBA** [comment]
Everything looks good to me. Great work.

**Comment by jhibbets** [comment]
This looks good to me. Great stuff, inpirational! Who would like to finalize this?

**Comment by ejaxon** [comment]
I'm on vacation for a week starting tomorrow, but happy to take a stab at finalizing after I'm back. I assume that, aside from flyers, etc., this will be used to populate a website? I think it would probably be good to add an FAQ that addresses questions like the relationship between Open NC and brigades, etc. They're sort of addressed in the later material that wouldn't actually go on a flyer. 

LMK if you want me to do the next pass after I'm back.

**Comment by ChrisTheDBA** [comment]
Eric,

I read through all your edits and approved most, if not all, of them.  Yes,
the two main purposes would be for the website and other collateral. I like
the idea of an FAQ page. If you want to take a shot at it. Go for it.

BTW, if anyone else is feeling prose-y - feel free to add to the doc as
well.

Chris Mathews
