### ISSUE TITLE
Reach out to Ryan about open-nc.org

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#4]
Get opennc.org transferred to Code for Charlotte - Ian

**Comment by IanHenshaw** [comment]
I sent Ryan an e-mail asking if we could get the following:

1. Transfer the open-nc.org URL to Code for Charlotte (they are now a 501(c)(3) organization).
2. Transfer ownership of the open-nc GitHub repositories (and the brigades could resurrect the project...?)
3. Transfer the twitter account.

**Comment by IanHenshaw** [comment]
Message from Ryan today. I will setup a meeting.

> This all sounds great. Let me know when you'd like to do this. We should also like to talk about how this change is getting communicated. I don't know that there's anyone who's going to look at anything currently branded Open-NC and wonder where it has gone, but I would like somewhere to preserve its heritage. I'm happy for it to be subsumed, inherited, etc. by the Artist Formerly Known as Code for NC.

**Comment by IanHenshaw** [comment]
Created new Issue for communication of Open-NC history (the rise and fall and now resurrection...)

**Comment by IanHenshaw** [comment]
Message from Ryan re: open-nc server:

> I obliterated open-nc.org a few months ago while trying to upgrade the OS, and I haven't been able to revive it.

**Comment by ChrisTheDBA** [comment]
Ryan and I need to sync schedules.
