### ISSUE TITLE
Document how to update website

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#41]
@christhedba can you put together a quick READ.ME file on how folks can update the website. Just a set of simple instructions so we have it documented. 

I am happy to be a tester during my website review.

**Comment by ChrisTheDBA** [comment]
The documentation is on the github repo - https://github.com/Open-NC/open-nc.github.io

**Comment by jhibbets** [comment]
I was thinking it might be nice to have something personalized for our group. Otherwise, we could end up in a situation where there are a limited number of people who have the ability to update the website. For example, it took me a hot minute to figure out how to and where to add a new image. I didn't see anything that said, go here and add a new image, I just kind of figured it out based on the blog template at the top of the MD file.
