### ISSUE TITLE
Clean-up slack and rename

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#6]
Make requested updates to Code for NC slack channel

**Comment by marshallj** [comment]
Currently, we have 19 Admins, and a Primary Owner in Slack.

I do not know many of the Admins.

Going forward, I recommend we have one designated team 'Owner' from each brigade, and other recommended brigade leadership be set to 'Admin' roles as needed. 

Admins should be selected based on leadership individuals that will need to invite members to the Slack Team.

## TODO Items:
[ ] Brigade Captains review list of existing Admins in the spreadsheet [here](https://docs.google.com/a/codeforgreensboro.org/spreadsheets/d/1NuRw0mGQIqEt-IU3X4_fDVGC9S8KI94Tz_IhA3axTnI/edit?usp=sharing), and recommend one Owner, and other leadership candidates that need Admin status. 
[ ] Mark individuals on the spreadsheet in your brigade that are currently an Admin, but do not need that level of access.
[ ] Add individuals to the list that need owner/admin status that are not on the list.

**Comment by ejaxon** [comment]
Updated my email in the spreadsheet and marked myself to be added as owner (if I'm not already). Nobody else from Code for Asheville to add for now.

**Comment by ChrisTheDBA** [comment]
We actually have an auto signup page here - https://code-for-nc-slack-invitations.herokuapp.com/

I will look at fixing this up. Been there since we branded the thing a few years ago.

**Comment by IanHenshaw** [comment]
Looks like you are an admin. Not sure how to assign owners...  I cannot
change peoples admin rights once they are an admin... Will talk to Robert
Campbell tomorrow or when his voice returns...
Cheers!
Ian

**Comment by IanHenshaw** [comment]
Invited Robert Campbell as a member for this GitHub account so we can assign task to Robert...

**Comment by rcampbellnc** [comment]
Changes to slack admin/owners implemented.

**Comment by IanHenshaw** [comment]
Slack URL changed to https://open-nc.slack.com
Slack Name changed to Open NC Collaborative
E-mail sent to all 254 members of the change

Note Slack policy on URL Change:

> Note: If you change your workspace’s URL, Slack will automatically redirect from the old to the new address. However, you should still make sure everyone in your workspace knows about the change because the old name will be placed back into the pool and could be used by some other workspace in the future.

**Comment by IanHenshaw** [comment]
Here is a good summary of the Roles and Permissions in Slack:
[https://get.slack.help/hc/en-us/articles/201314026-Roles-and-permissions-in-Slack](url)

**Comment by rcampbellnc** [comment]
Owners and Admins update completed.
