### ISSUE TITLE
Rename data.world to Open NC Collaborative (or just Open NC)

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#8]

**Comment by ChrisTheDBA** [comment]
Don't believe I can do this, but I will get with Bill Scanlon to do so

**Comment by jhibbets** [comment]
Pinged Bill to ask for Admin access

**Comment by jhibbets** [comment]
I now have admin access and was able to change the ORG name, but not the URL. I submitted a support ticket to request the URL be changed.

**Comment by jhibbets** [comment]
Unfortunately, we don't yet have a way to change the URL of an organization. From looking at how it's currently setup, my recommendation would be to create a new organization with the name that you want, and then add the Contributors that are a part of the current one, as well as add the datasets that are referenced by it. You can then delete the old organization.

I understand the need for a more seamless process here but for now, I believe that's the best path forward. Please let me know if you have any concerns.

Cheers!
Dashiel
data.world team
