### ISSUE TITLE
Make GitHub pages for website 

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#9]
Build a website with current information to all brigades and launched projects

This is for colin

**Comment by jhibbets** [comment]
I looked at the site and it's a great start. How do we update / remove the social media icons in the footer?

**Comment by ChrisTheDBA** [comment]
On the main page -
https://github.com/Open-NC/open-nc.github.io#contact-information


   - Social media links and icons are managed through _config.yml.



Chris Mathews
